export const projects = [
  {
    title: "Upkeepr",
    description:
      "The Upkeepr is an American startup that helps create item-centric plans, get things done, and live life well. I allow to keep item details, warranty info, and receipts easily accessible, create upkeep plans to avoid breakdowns and expensive repairs.",
    accomplishments: [
      "migrated REST api to Apollo GraphQl",
      "integrated Apollo GraphQL in a right way (move most state from redux to Apollo Cache)",
      "implemented sophisticated google inspired due date notification UI",
      "implemented authentication with Auth0 and refresh tokens",
    ],
    techTags: [
      "React",
      "Apollo",
      "Apollo Client",
      "Redux",
      "styled-components",
      "Microsoft azure",
      "PWA",
      "Typescript",
    ],
    projectLink: "https://upkeepr.com",
  },
  {
    title: "Pafory",
    description:
      "Pafory.com - is a german e-commerce website specialising in perfumes. The main feature is the subscription feature. Also, you have the ability to find perfume, that suites you using a perfume finder feature. ",
    accomplishments: [
      "created front-end architecture",
      "lead of front-end team",
      "close collaboration with backend team to design API",
      "implemented perfume finder",
      "implemented subscription calendar",
      "implemented auth",
      "implemented internationalisation",
      "integrated payment providers (Braintree, Amazon Pay)",
    ],
    techTags: [
      "Next.js",
      "REST API",
      "Typescript",
      "CSS",
      "Braintree",
      "Amazon Pay",
    ],
    projectLink: "https://pafory.com",
  },
  {
    title: "Expetitle",
    description:
      "Expetitle - American startup which helps title agents automate internal processes when making operations with real estate. Was acquired by The Real Brokerage.",
    accomplishments: [
      "Lead frontend developer",
      "created front-end architecture",
      "implemented sophisticated drag and drop experience (Asana like cards)",
      "implemented getting server data with REST and GraphQl and ReactQuery caching",
      "implemented web-socket data live updates",
      "built cookies based cross-domain authentication",
    ],
    techTags: [
      "Next.js",
      "Typescript",
      "REST API",
      "GraphQL",
      "Web Scokets",
      "Styled-components",
      "Material-UI",
      "OAuth",
    ],
    projectLink: "https://expetitle.com",
  },
  {
    title: "EF speak",
    description:
      "EF-speak is student-powered student engagement platform. The main feature is voice recognition and analysis which could evaluate your pronunciation. ",
    accomplishments: [
      "Back-end developer",
      "wrote unit and integration tests",
      "architect module with polymorphic associations in database",
      "helped lead developer with resolvers",
      "implemented abstraction for pagination and sorting",
      "heavy use of typescript decorators",
    ],
    techTags: [
      "Node.js",
      "PostgreSQL",
      "SQLight",
      "Swquilize ORM",
      "Express.js",
      "Unit testing",
      "Apollo GraphQL",
      "Apollo Server",
      "Microservices",
    ],
    projectLink: "https://speak.ef.com",
  },
  {
    title: "Media Flow",
    description:
      "MediaFlow is the early startup for automating workflow of advertising agencies.",
    accomplishments: [
      "Lead Full-stack developer",
      "created front-end and back-end architecture",
      "implemented fully type-safe backend and frontend",
      "implemented serverless architecture",
      "used cutting edge tech stack - Next.JS, TRPC, Prisma, Planetscale, Tailwind",
      "integrated AWS S3 as a files storage",
      "build front-end component library (Tailwind + HeadlessUI)",
    ],
    techTags: [
      "Next.Js",
      "Next Auth",
      "PlanetScale",
      "TRPC",
      "create-t3-stack",
      "Tailwind CSS",
      "Prisma.js",
      "AWS S3",
      "React Table",
    ],
  },
  // {
  //   title: "",
  //   description: "",
  //   accomplishments: [],
  //   techTags: [],
  //   projectLink: "",
  // },
];
